/// Flutter icons TraininIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TraininIcons
///      fonts:
///       - asset: fonts/TraininIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TraininIcons {
  TraininIcons._();

  static const _kFontFam = 'TraininIcons';
  static const String? _kFontPkg = null;

  static const IconData back = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbell = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData options = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData go_to = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kcal = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
